!<Lines>
name: Train time vs subset
group_by: [model, params, cluster_name, nthreads]
legend_labels: !!python/name:Benchmarker.utils.legend_label_fg ''
style: o-
title: Training Time vs Subset Fraction
y_col: trainTime
ylab: Training time [s]
x_col: subset
xlab: Subset Fraction
